spring:
  application:
    name: notesmarketplace

  datasource:
    url:  ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

sslcommerz:
  store-id: ${SSLCOMMERZ_STORE_ID}
  store-password: ${SSLCOMMERZ_STORE_PASSWORD}
  base-url: ${SSLCOMMERZ_BASE_URL}
  success-url: ${SSLCOMMERZ_SUCCESS_URL}
  fail-url: ${SSLCOMMERZ_FAIL_URL}
  cancel-url: ${SSLCOMMERZ_CANCEL_URL}
